uncompleted_blocks = [
  {'id': 0,  'start_spot': (0, 0), 'length': 6, 'dimension': 'across'},
  {'id': 1,  'start_spot': (0, 7), 'length': 3, 'dimension': 'across'},
  {'id': 2,  'start_spot': (1, 0), 'length': 6, 'dimension': 'across'},
  {'id': 3,  'start_spot': (1, 7), 'length': 4, 'dimension': 'across'},
  {'id': 4,  'start_spot': (2, 0), 'length': 6, 'dimension': 'across'},
  {'id': 5,  'start_spot': (2, 7), 'length': 4, 'dimension': 'across'},
  {'id': 6,  'start_spot': (3, 2), 'length': 3, 'dimension': 'across'},
  {'id': 7,  'start_spot': (3, 8), 'length': 3, 'dimension': 'across'},
  {'id': 9,  'start_spot': (4, 8), 'length': 3, 'dimension': 'across'},
  {'id': 11, 'start_spot': (6, 0), 'length': 3, 'dimension': 'across'},
  {'id': 13, 'start_spot': (7, 0), 'length': 3, 'dimension': 'across'},
  {'id': 14, 'start_spot': (7, 6), 'length': 3, 'dimension': 'across'},
  {'id': 15, 'start_spot': (8, 0), 'length': 4, 'dimension': 'across'},
  {'id': 16, 'start_spot': (8, 5), 'length': 6, 'dimension': 'across'},
  {'id': 17, 'start_spot': (9, 0), 'length': 4, 'dimension': 'across'},
  {'id': 18, 'start_spot': (9, 5), 'length': 6, 'dimension': 'across'},
  {'id': 19, 'start_spot': (10, 1),'length': 3, 'dimension': 'across'},
  {'id': 20, 'start_spot': (10, 5),'length': 6, 'dimension': 'across'},
  {'id': 21, 'start_spot': (0, 0), 'length': 3, 'dimension': 'down'  },
  {'id': 22, 'start_spot': (4, 0), 'length': 6, 'dimension': 'down'  },
  {'id': 23, 'start_spot': (0, 1), 'length': 3, 'dimension': 'down'  },
  {'id': 24, 'start_spot': (4, 1), 'length': 7, 'dimension': 'down'  },
  {'id': 25, 'start_spot': (0, 2), 'length': 11,'dimension': 'down'  },
  {'id': 26, 'start_spot': (0, 3), 'length': 6, 'dimension': 'down'  },
  {'id': 27, 'start_spot': (8, 3), 'length': 3, 'dimension': 'down'  },
  {'id': 28, 'start_spot': (0, 4), 'length': 7, 'dimension': 'down'  },
  {'id': 29, 'start_spot': (0, 5), 'length': 3, 'dimension': 'down'  },
  {'id': 30, 'start_spot': (4, 5), 'length': 3, 'dimension': 'down'  },
  {'id': 31, 'start_spot': (8, 5), 'length': 3, 'dimension': 'down'  },
  {'id': 32, 'start_spot': (4, 6), 'length': 7, 'dimension': 'down'  },
  {'id': 33, 'start_spot': (0, 7), 'length': 3, 'dimension': 'down'  },
  {'id': 34, 'start_spot': (5, 7), 'length': 6, 'dimension': 'down'  },
  {'id': 35, 'start_spot': (0, 8), 'length': 11,'dimension': 'down'  },
  {'id': 36, 'start_spot': (0, 9), 'length': 7, 'dimension': 'down'  },
  {'id': 37, 'start_spot': (8, 9), 'length': 3, 'dimension': 'down'  },
  {'id': 38, 'start_spot': (1, 10),'length': 6, 'dimension': 'down'  },
  {'id': 39, 'start_spot': (8, 10),'length': 3, 'dimension': 'down'  }
]